import type { Metadata } from "next";
import "./globals.css";
import { Work_Sans, Raleway } from "next/font/google";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

// Work Sans setup
const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-work-sans",
  display: "swap",
});

// Raleway setup
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-raleway",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} ${raleway.variable} antialiased`}>
        <div className="w-full text-textColor">
          <div className="bg-yellow-500 wrapper font-sans">
            <Navbar></Navbar>
            <div>
              {children}
            </div>
            <Footer></Footer>
          </div>
        </div>
      </body>
    </html>
  );
}
