import type { Metadata } from "next";
import "./globals.css";
import { Work_Sans, Raleway } from "next/font/google";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { ThemeContextProvider } from "@/components/shared/ThemeContext";
import ThemeProvider from "@/components/shared/ThemeProvider";
import AuthProvider from "@/components/shared/AuthProvider";

// Work Sans setup
const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-work-sans",
  display: "swap",
});

// Raleway setup
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-raleway",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bloggers'",
  description: "Generated by Md. Mehedi Hasan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} ${raleway.variable} antialiased`}>
        <AuthProvider>

          <ThemeContextProvider>
            <ThemeProvider>
              <div className="w-full text-textColor bg-bg">
                <div className="wrapper font-sans">
                  <Navbar></Navbar>
                  <div className="min-h-[calc(100vh-100px)] pt-[100px] sm:pt-0">
                    {children}
                  </div>
                  <div className="border-t-[1px] border-bgSoft mt-20">
                    <Footer></Footer>
                  </div>
                </div>
              </div>
            </ThemeProvider>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
